import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(allow_unicode=True, blank=True, max_length=130, unique=True)),
                ("image", models.ImageField(blank=True, upload_to="categories/")),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="children", to="shop.category")),
            ],
            options={"verbose_name_plural": "دسته‌بندی‌ها", "ordering": ["sort_order", "name"]},
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("site_name", models.CharField(default="سنا", max_length=80)),
                ("tagline", models.CharField(default="جزئیات کوچک، حس بزرگ", max_length=180)),
                ("announcement", models.CharField(blank=True, default="ارسال رایگان برای خریدهای بالای ۲ میلیون تومان", max_length=220)),
                ("logo", models.ImageField(blank=True, upload_to="branding/")),
                ("primary_color", models.CharField(default="#7b243f", max_length=7)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("instagram", models.CharField(blank=True, max_length=80)),
                ("telegram", models.CharField(blank=True, max_length=80)),
                ("address", models.TextField(blank=True)),
                ("payment_mode", models.CharField(choices=[("zarinpal", "زرین‌پال"), ("card", "کارت به کارت"), ("both", "هر دو")], default="card", max_length=12)),
                ("zarinpal_merchant_id", models.CharField(blank=True, default="", max_length=64)),
                ("zarinpal_sandbox", models.BooleanField(default=False)),
                ("card_number", models.CharField(blank=True, default="", max_length=24)),
                ("card_owner", models.CharField(blank=True, default="", max_length=100)),
                ("shipping_fee", models.PositiveBigIntegerField(default=90000)),
                ("free_shipping_threshold", models.PositiveBigIntegerField(default=2000000)),
                ("enamad_html", models.TextField(blank=True, help_text="کد HTML دریافت‌شده از اینماد")),
                ("terms_text", models.TextField(blank=True)),
                ("return_policy", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True)),
                ("sku", models.CharField(blank=True, max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("price", models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("compare_at_price", models.PositiveBigIntegerField(blank=True, null=True)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("image", models.ImageField(blank=True, upload_to="products/%Y/%m/")),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="products", to="shop.category")),
            ],
            options={"ordering": ["-is_featured", "-created_at"]},
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(editable=False, max_length=16, unique=True)),
                ("full_name", models.CharField(max_length=120)),
                ("mobile", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("province", models.CharField(max_length=80)),
                ("city", models.CharField(max_length=80)),
                ("address", models.TextField()),
                ("postal_code", models.CharField(max_length=20)),
                ("note", models.TextField(blank=True)),
                ("subtotal", models.PositiveBigIntegerField(default=0)),
                ("shipping", models.PositiveBigIntegerField(default=0)),
                ("total", models.PositiveBigIntegerField(default=0)),
                ("payment_method", models.CharField(choices=[("zarinpal", "زرین‌پال"), ("card", "کارت به کارت")], max_length=12)),
                ("status", models.CharField(choices=[("pending", "در انتظار پرداخت"), ("review", "بررسی پرداخت"), ("paid", "پرداخت‌شده"), ("processing", "در حال آماده‌سازی"), ("shipped", "ارسال‌شده"), ("cancelled", "لغوشده")], default="pending", max_length=16)),
                ("authority", models.CharField(blank=True, max_length=64)),
                ("payment_ref_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="products/%Y/%m/")),
                ("alt", models.CharField(blank=True, max_length=180)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="gallery", to="shop.product")),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=180)),
                ("unit_price", models.PositiveBigIntegerField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="shop.order")),
                ("product", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="shop.product")),
            ],
        ),
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="receipts/%Y/%m/")),
                ("status", models.CharField(choices=[("pending", "در انتظار"), ("approved", "تاییدشده"), ("rejected", "ردشده")], default="pending", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="receipt", to="shop.order")),
            ],
        ),
    ]
